// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShareIt.Infrastructure.Persistence;

#nullable disable

namespace ShareIt.Infrastructure.Persistence.Migrations.Sqlite
{
    [DbContext(typeof(ShareItDbContext))]
    [Migration("20260924152012_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ShareIt.Core.Models.BrowserGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrowserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "BrowserId")
                        .IsUnique();

                    b.ToTable("BrowserGrant");
                });

            modelBuilder.Entity("ShareIt.Core.Models.CleanupTask", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PurgeRequested")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.HasIndex("NextAttemptAtUtc");

                    b.ToTable("CleanupTask");
                });

            modelBuilder.Entity("ShareIt.Core.Models.FileEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("SessionId", "Number")
                        .IsUnique();

                    b.ToTable("Files");
                });

            modelBuilder.Entity("ShareIt.Core.Models.SharedSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("NextFileNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextTextNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("ShareIt.Core.Models.TextCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Number")
                        .IsUnique();

                    b.ToTable("TextCard");
                });

            modelBuilder.Entity("ShareIt.Core.Models.BrowserGrant", b =>
                {
                    b.HasOne("ShareIt.Core.Models.SharedSession", null)
                        .WithMany("Grants")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShareIt.Core.Models.CleanupTask", b =>
                {
                    b.HasOne("ShareIt.Core.Models.SharedSession", null)
                        .WithOne("Cleanup")
                        .HasForeignKey("ShareIt.Core.Models.CleanupTask", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShareIt.Core.Models.FileEntry", b =>
                {
                    b.HasOne("ShareIt.Core.Models.SharedSession", null)
                        .WithMany("Files")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShareIt.Core.Models.TextCard", b =>
                {
                    b.HasOne("ShareIt.Core.Models.SharedSession", null)
                        .WithMany("Texts")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShareIt.Core.Models.SharedSession", b =>
                {
                    b.Navigation("Cleanup")
                        .IsRequired();

                    b.Navigation("Files");

                    b.Navigation("Grants");

                    b.Navigation("Texts");
                });
#pragma warning restore 612, 618
        }
    }
}
